- implement a method to make sure the record for "yesterday" is marked off, in order to figure out streak number
- integrate streak level (easy, medium, hard) to habit
- figure out a way to display when a habit has hit the goal of a streak level
- "tab" between Modify/View/Add (?)
- Change color upon selecting color in modify, as opposed to clicking away from select
